### ISSUE TITLE
Everyone using same Prettier settings

### ISSUE THREAD

**Issue by nicolehli** [FreshPrice/Fresh#18]
Hey team, let's all use the same Prettier settings so we don't have linting commit changes. I've attached what I'm using. Any disagreements?

Quotation specific settings:
<img width="1345" alt="Screen Shot 2019-06-15 at 4 24 41 PM" src="https://user-images.githubusercontent.com/17561746/59557274-58d31c80-8f8a-11e9-824e-3dda5e15cadd.png">

Prettier settings:

<img width="1345" alt="Screen Shot 2019-06-15 at 4 20 53 PM" src="https://user-images.githubusercontent.com/17561746/59557240-ad29cc80-8f89-11e9-94c0-d859d6d4c5ef.png">
<img width="1345" alt="Screen Shot 2019-06-15 at 4 20 59 PM" src="https://user-images.githubusercontent.com/17561746/59557241-ae5af980-8f89-11e9-8a49-6ebd742ca67d.png">
<img width="1345" alt="Screen Shot 2019-06-15 at 4 21 07 PM" src="https://user-images.githubusercontent.com/17561746/59557244-b3b84400-8f89-11e9-808f-120cafd065fa.png">
<img width="1345" alt="Screen Shot 2019-06-15 at 4 21 17 PM" src="https://user-images.githubusercontent.com/17561746/59557246-b61a9e00-8f89-11e9-8619-4ddc8fa01509.png">

**Comment by YaoLiu93** [comment]
Do you have a prettier rc? could just check that in

**Comment by inquisitiv-e** [comment]
![Screen Shot 2019-06-15 at 4 53 38 PM](https://user-images.githubusercontent.com/44586417/59557406-2d523100-8f8e-11e9-8ebe-f5b2df940142.png)

**Comment by nicolehli** [comment]
Yea i found the dot rc role but it only had few lines, :/

**Comment by nicolehli** [comment]
I think we are all good now. So closing this ticket.
