### ISSUE TITLE
Bug fixes for next sprint

### ISSUE THREAD

**Issue by inquisitiv-e** [FreshPrice/Fresh#27]
- The word-wrap overflows out of the details part of the card.

- Making the location field required. The library doesn't support "required" prop, so need to come up with alternatives

- The location drop-down is transparent

**Comment by YaoLiu93** [comment]
If appears that react-auto-complete can use search options to focus the search
https://www.npmjs.com/package/react-places-autocomplete#searchoptions

Can you incorporate that to our search to focus down on just the lower mainland?

**Comment by inquisitiv-e** [comment]
- Fix diff vuln

**Comment by inquisitiv-e** [comment]
![Screen Shot 2019-06-29 at 12 00 56 AM](https://user-images.githubusercontent.com/44586417/60380857-fbff4980-9a00-11e9-8fba-315f478f5cd4.png)
Markers disappear upon search

**Comment by inquisitiv-e** [comment]
> If appears that react-auto-complete can use search options to focus the search
> https://www.npmjs.com/package/react-places-autocomplete#searchoptions
> 
> Can you incorporate that to our search to focus down on just the lower mainland?

Done!
