### ISSUE TITLE
Bug fixes for next sprint

### ISSUE THREAD

**Issue by inquisitiv-e** [FreshPrice/Fresh#28]

**Comment by inquisitiv-e** [comment]
The word-wrap overflows out of the details part of the card.

Making the location field required. The library doesn't support "required" prop, so need to come up with alternatives

The location drop-down is transparent

**Comment by inquisitiv-e** [comment]
![Screen Shot 2019-06-29 at 12 00 56 AM](https://user-images.githubusercontent.com/44586417/60389582-170da000-9a79-11e9-9443-b71e50092868.png)
Marker disappears upon search

**Comment by nicolehli** [comment]
I'm not sure what was added, but first card have missing item and price says $h:

Issue found on Master on commit cbea346febadf723d4c9e612d61f7a5e6f97a315
![image](https://user-images.githubusercontent.com/17561746/60390567-5397c680-9a8e-11e9-939d-99867c1a9303.png)

**Comment by inquisitiv-e** [comment]
> I'm not sure what was added, but first card have missing item and price says $h:
> 
> Issue found on Master on commit [cbea346](https://github.com/FreshPrice/Fresh/commit/cbea346febadf723d4c9e612d61f7a5e6f97a315)
> ![image](https://user-images.githubusercontent.com/17561746/60390567-5397c680-9a8e-11e9-939d-99867c1a9303.png)

I added that by accident yesterday! We should delete it

**Comment by YaoLiu93** [comment]
Erica, those markers didn't disappear. We can't see them because they're location is not in Vancouver. Try zooming out!

**Comment by inquisitiv-e** [comment]
> Erica, those markers didn't disappear. We can't see them because they're location is not in Vancouver. Try zooming out!

Ahh you're right! I got confused because I thought the "Hokkaido" in the image was referring to the Hokkaido Ramen Santouka on the map

**Comment by nicolehli** [comment]
Moved unfinished checkbox items into #37
