### ISSUE TITLE
Add item cleanup for items older than ??? days

### ISSUE THREAD

**Issue by YaoLiu93** [FreshPrice/Fresh#53]
The price of groceries is not static. Maybe we want to add the ability to prune or set inactive some items which are older than ??? days. 
- [ ] Add ability to self-prune database depending on created time.

**Comment by inquisitiv-e** [comment]
This is a good feature but I'm not sure how we can show that this works during the final demo.

**Comment by YaoLiu93** [comment]
Out of scope for demo, nice to consider for future.
