### ISSUE TITLE
Project Progress Due July 20th

### ISSUE THREAD

**Issue by nicolehli** [FreshPrice/Fresh#57]
- [x] Run meteor remove insecure on your project, which will prevent you from editing the
database straight from the client. Then, re-write parts of your app in order to get it
working again! Make sure everything works before moving on to the next step.
https://www.meteor.com/tutorials/react/security-with-methods

- [x] Run meteor remove autopublish on your project, which will stop automatically sending
all of the data to the client. Then, re-write parts of your app in order to get it working
again. Make sure everything works before moving on to write more functionality.
https://www.meteor.com/tutorials/react/publish-and-subscribe

- [x] Write a quick, 2 sentence high-level description of your project for someone who has
never seen your project before, and put it in your README. This will go to the industry
guests, so please make sure that it is suitable for posting publicly.

- [x] Take a look at your goals and regroup them into achievable tasks. 5 weeks left.

Second: Get styling done / logo / aligning etc!! lots. :black_square_button: :black_square_button: :black_square_button:

Third: Maybe start stretch goals or polish things…

week 30: Aim to finish? Or work on stretch goals? Fix/Polish things

- User can create shopping lists using the posts items. :black_square_button:
- User can watch an item and get notified when prices are lower than their set price. :black_square_button:
week 31: Update README/Testing/Prepare Demo Poster etc. :black_square_button:
week 32: Demo !!! 

- [ ] branch project_5

**Comment by inquisitiv-e** [comment]
Things to talk about during Demo
- Style changes
- Form validation -> submit form button disabled until all fields are filled out with correct values.
