### ISSUE TITLE
Project Process Due June 8th

### ISSUE THREAD

**Issue by nicolehli** [FreshPrice/Fresh#7]
App/Map (@YaoLiu93 )

App/CardList
* filter/search
* search bar
* card (@inquisitiv-e)
* new card button (@YaoLiu93)
* *  Modal (@nicolehli)

**Comment by YaoLiu93** [comment]
Initial structuring:

App/Map completed. https://github.com/FreshPrice/Fresh/pull/10
Card completed. https://github.com/FreshPrice/Fresh/pull/9
New card button completed. https://github.com/FreshPrice/Fresh/pull/10
Modal completed. https://github.com/FreshPrice/Fresh/pull/8

**Comment by nicolehli** [comment]
Great job everyone! On to next sprint :)
