### ISSUE TITLE
About Us page

### ISSUE THREAD

**Issue by nicolehli** [FreshPrice/Fresh#70]
It would be nice to link our github repo, and us three's social media on the project

**Comment by YaoLiu93** [comment]
Do you think we need a page? Or enough to just it in as a footer?

**Comment by nicolehli** [comment]
Woo footer might be nice too. Like one of those Created by something. Or Made with love from Vancouver, sometimes I see that haha.

**Comment by YaoLiu93** [comment]
Yeeeeh! Do you want to work on that?
