### ISSUE TITLE
Re-write introduction

### ISSUE THREAD

**Issue by nicolehli** [FreshPrice/Fresh#71]
Fresh is the hottest crowd-sourced grocery store price reporting app around.

Fresh is a web application that helps consumers make cost-friendly choices for groceries. Users can post grocery prices, locations and images to the app, and see reported deals submitted by other people. Leave thumbs up or down to help validate posts. Compare the prices of groceries through the search and sort features. When you find a deal that you like, bookmark them for later and see them in the shopping list.

To do:
- Make this two to three sentences. Ideally two. 
- What it is / How it does it (the solution) / Why do we want it (the problem)

**Comment by nicolehli** [comment]
1) **Fresh** is a crowd-sourcing web platform to help users find and report the lowest grocery prices. When you find a deal, bookmark them for later and see them in the shopping list.

**Comment by nicolehli** [comment]
2. Fresh uses grocery price information provided by our users to bring shoppers together to support the common goal of saving money on groceries. User can report, vote, search, sort and save grocery deals.

**Comment by YaoLiu93** [comment]
3. Fresh is the hottest crowd-sourced grocery price sharing app around. Our wholesome users can contribute fresh deal discoveries, search and sort through current deals, rate them and even save deals for shopping later!

**Comment by inquisitiv-e** [comment]
Fresh is the hottest crowd-sourced grocery price sharing app around. Shoppers can report fresh deals, search and sort through current deals, rate them and even save deals for shopping later!

Combining your ideas

**Comment by YaoLiu93** [comment]
Fresh is the hottest crowd-sourced grocery price sharing app around. Shoppers can contribute fresh deals, search and sort through current deals, rate them and even save deals for shopping later!

If this works, thumbs it up and we'll let the course staff know ASAP.

**Comment by nicolehli** [comment]
6. Fresh is a crowd-sourcing web platform to help users find and report the lowest grocery prices. Shoppers can contribute new deals, search and sort through reported deals, and even rate or save deals for shopping later! 

Another stab ^

- This one has no 'hottest' because someone gave us feedback it sounded very commercial
- Also trying to add what the problem we're solving with the find/report 'lowest grocery prices' part

**Comment by YaoLiu93** [comment]
Crowd-sourcing makes it sound like we're in the business of getting crowd-sourcing, like gofund me. ]

Thoughts?

Fresh is a crowd-sourced web platform which allows users to find and share amazing grocery prices. Shoppers can contribute new deals, rate, search and sort on reported deals, or save deals for shopping later!

**Comment by nicolehli** [comment]
> Crowd-sourcing makes it sound like we're in the business of getting crowd-sourcing, like gofund me.
> 
> Thoughts?
> 
> Fresh is a crowd-sourced web platform which allows users to find and share amazing grocery prices. Shoppers can contribute new deals, rate, search and sort on reported deals, or save deals for shopping later!

Gofundme and kickstarter does crowd-funding, not crowd-sourcing.

**Comment by YaoLiu93** [comment]
Ooooooooh yes LOL. Whoops.

**Comment by YaoLiu93** [comment]
Submitted:

>Fresh is a crowd-sourced web platform which allows users to find and share amazing grocery prices. Shoppers can contribute new deals, rate, search and sort on reported deals, or save deals for shopping later!
