### ISSUE TITLE
Delete shopping list item

### ISSUE THREAD

**Issue by inquisitiv-e** [FreshPrice/Fresh#76]
Add to shopping list could add item multiple times when google between + icon and ✔️icon.  Also going from + to ✔️  doesn't remove the item from the shopping cart list. Do we want a way to remove items from shopping cart?

_Originally posted by @nicolehli in https://github.com/FreshPrice/Fresh/pull/73_

**Comment by YaoLiu93** [comment]
@inquisitiv-e Actively working on this? :D

**Comment by inquisitiv-e** [comment]
FINISHED
